apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-job
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: backup
        spec:
          containers:
            - name: backup
              image: backup-image:v1.0
              command: ["/bin/sh", "-c", "backup-script.sh"]
          restartPolicy: OnFailure
